### ISSUE TITLE
Change this to not be set manually

### ISSUE THREAD

**Issue by steevejoseph** [Group-26-MAARS/Challenge1_PathNav#1]
https://github.com/Group-26-MAARS/Challenge1_PathNav/blob/b1493fe390a3da9762cab40f69352b0bd2089c38/Assets/PathNav/Scripts/AzureSpatialAnchorsCreateOnly.cs#L36

**Comment by dtroberts1** [comment]
Thanks Steeve. Feel free to create tasks for whatever else you see that I need to address.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by dtroberts1** [comment]
Issue fixed. App now allows any number of anchors to be used for navigation
